name: CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Usa la misma versión que tu Lambda
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
      - name: Run tests
        run: |
          source env/bin/activate
          pytest
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Check if Lambda function exists
        id: check_function
        run: |
          source env/bin/activate
          FUNCTION_NAME=$(python -c "
          import json
          with open('zappa_settings.json', 'r') as f:
              config = json.load(f)
              print(config['dev']['project_name'] + '-dev')
          ")
          echo "Function name: $FUNCTION_NAME"
          if aws lambda get-function --function-name $FUNCTION_NAME 2>/dev/null; then
            echo "function_exists=true" >> $GITHUB_OUTPUT
          else
            echo "function_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Deploy with Zappa (first time)
        if: steps.check_function.outputs.function_exists == 'false'
        run: |
          source env/bin/activate
          zappa deploy dev
      - name: Update with Zappa (existing function)
        if: steps.check_function.outputs.function_exists == 'true'
        run: |
          source env/bin/activate
          zappa update dev


